import type { Metadata } from 'next';
import './globals.css';
import { LayoutWrapper } from '@/components/layouts/LayoutWrapper';
import Modal from '@/components/shared/Modal';
import Snackbar from '@/components/shared/Snackbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" dir="rtl">
      <body>
        <LayoutWrapper>
          <Modal />
          <Snackbar />
          {children}
        </LayoutWrapper>
      </body>
    </html>
  );
}
